services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # --- Repositories ---
    App\Membership\Model\MemberAccountRepository:
        class: App\Infrastructure\InMemoryMemberAccountRepository

    App\Membership\Model\Reward\RewardCatalog:
        class: App\Infrastructure\InMemoryRewardCatalog

    # --- Event Handlers ---
    App\Membership\Handler\EventLogger: ~
